NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-103-CA3.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-103-CA3.pem
    OrganizationalUnitIdentifier: client
  AdminOUIdentifier:
    Certificate: cacerts/localhost-103-CA3.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-103-CA3.pem
    OrganizationalUnitIdentifier: orderer
